### ISSUE TITLE
Add templates using the Apify SDK for Python

### ISSUE THREAD

**Issue by fnesveda** [apify/actor-templates#111]
After we have the Apify SDK for Python implemented, we need to add actor templates that will use it.

There two main decisions / tasks:
- [x] which templates to add
	- plain
	- BeautifulSoup
	- Scrapy
	- Selenium
	- Playwright
	- others?
- [x] project structure - done in #118
	- should it use `pyproject.toml`?
	- where will the main script be defined? (equivalent to `package.json : scripts : start`)
	- should they use a virtual environment
		- would be really good for local running
		- not needed for running on platform, but won't hurt

**Comment by metalwarrior665** [comment]
@fnesveda Do you have a plan for how to do the Scrapy-to-actor mapping as their structure is more complicated than Crawlee's? They have multiple spiders per folder with top-level libraries if I recall so they would need to select the spider via input or somehow CD into it in Dockerfile?

**Comment by fnesveda** [comment]
No plan yet. I think we can have the template simple, optimized just for one spider, and solve these complicated things in the scrapy migrator.

The Scrapy "multiple spiders per project" philosophy does not really align with the "do just one thing but do it well" UNIX (and actor) philosophy.
