### ISSUE TITLE
Templates have Input schema but don't use input at all

### ISSUE THREAD

**Issue by metalwarrior665** [apify/actor-templates#114]
This is especially confusing on the platform where you can change the input but it doesn't affect the run.

Not sure if we want to force filling the input since users would need to add it locally but maybe we can do something like

```
const { startUrls } = await Apify.getInput() || { startUrls: ['https://apify.com'] };
```

But actually if you create actor with templates, it already does create the storage + INPUT, right?

**Comment by fnesveda** [comment]
@jbartadev This was on our team for some reason, but I guess you're mostly solving this with your template updates, right?

**Comment by jbartadev** [comment]
@fnesveda yes, we're dealing with this with the template and CLI updates.

**Comment by fnesveda** [comment]
Thanks, I assigned it to `t-web` 🙂

**Comment by B4nan** [comment]
I guess this one is resolved nowadays @jbartadev?
