### ISSUE TITLE
`js-langchain` template tests are failing

### ISSUE THREAD

**Issue by jbartadev** [apify/actor-templates#263]
@B4nan says: started failing a week ago, looks like the token is no longer present or valid

edit: or maybe its just about the removed model, seeing NotFoundError: 404 The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations in there

**Comment by jbartadev** [comment]
@mtrunkat Máro, can you please take a look?

**Comment by B4nan** [comment]
Or maybe @jirimoravcik could know what to do? 🙏

**Comment by mtrunkat** [comment]
@jirimoravcik or @drobnikj - what would be the best model to replace deprecated davinci?

**Comment by jirimoravcik** [comment]
> @jirimoravcik or @drobnikj - what would be the best model to replace deprecated davinci?

I'd go with `gpt-3.5-turbo`
