### ISSUE TITLE
The langchain template is outdated, the tests are still passing but print some deprecation warnings

### ISSUE THREAD

**Issue by jirispilka** [apify/actor-templates#290]
Raised at [slack](https://apify.slack.com/archives/C04URRT3934/p1725439824642109)

**Comment by B4nan** [comment]
next time add `Closes #...` to the PR description so its connected to the issue and autocloses it

**Comment by jirispilka** [comment]
> next time add `Closes #...` to the PR description so its connected to the issue and autocloses it

oh, I'm sorry, missed that. Thanks!
