### ISSUE TITLE
Need guidance on structuring CLI commands and organizing __main__.py logic

### ISSUE THREAD

**Issue by muhammedadnanv** [apify/actor-templates#300]
I want to implement multiple CLI commands in my project using a library like click. Currently, I have logic in __main__.py, but I'm unsure about the best way to:

Reorganize the __main__.py logic to support multiple commands
Structure the code to have separate commands for:
Running actors/spiders
Other functionality
Current Situation
Have logic in __main__.py
Want to use click or similar for CLI commands
Need to support multiple commands
Questions
What's the recommended way to structure the CLI commands?
How should the __main__.py logic be split/moved?
What's the best practice for organizing command-related code in the project?
Example Use Case
Would like to support commands like:

bash

Verify

Open In Editor
Edit
Copy code
my-tool run-actor
my-tool other-command
Related Issues
apify/apify-sdk-python#176
Would appreciate guidance on the best practices for this kind of setup.

 enhancement, documentation, good first issue

**Comment by B4nan** [comment]
Thanks for the suggestion, but we already have https://github.com/apify/apify-cli for this, no need to make the templates more complicated, they are templates, not CLI apps.
