### ISSUE TITLE
 Implement CLI Command Structure with Click Integration

### ISSUE THREAD

**Issue by muhammedadnanv** [apify/actor-templates#301]
Following up on the CLI organization discussion, we should implement a proper command-line interface using Click. This will provide a better user experience and more organized command structure.

Proposed Implementation
Create a new cli module with the following structure:

Verify

Open In Editor
Edit
Copy code
project/
├── cli/
│   ├── __init__.py
│   ├── commands/
│   │   ├── __init__.py
│   │   ├── actor.py
│   │   └── other_commands.py
│   └── main.py
Move existing __main__.py logic into appropriate command modules
Implement core CLI group using Click:
python

Verify

Open In Editor
Edit
Copy code
# cli/main.py
import click

@click.group()
def cli():
    """Main CLI entry point"""
    pass

# Add commands
cli.add_command(actor_commands.run)
cli.add_command(other_commands.something)
Tasks
 Create basic CLI structure
 Move actor/spider running logic to commands/actor.py
 Implement basic command group with Click
 Add tests for CLI commands
 Update documentation with CLI usage examples
Expected Usage
bash

Verify

Open In Editor
Edit
Copy code
# Running an actor
$ project run-actor [options]

# Other commands
$ project other-command [options]
Benefits
Better organized code structure
Easier to add new commands
Improved help documentation through Click
More maintainable codebase

**Comment by B4nan** [comment]
Closing this one as well, I don't understand how it's different from the other issue you created.
