### ISSUE TITLE
Extend the simplest example

### ISSUE THREAD

**Issue by jancurn** [apify/actor-templates#55]
The current one is a bit blunt. Maybe we can reuse this one: https://github.com/apify/apify-core/pull/974

**Comment by mnmkng** [comment]
Which one is the simplest example?

**Comment by jancurn** [comment]
I meant the hello world one: https://github.com/apify/actor-templates/blob/master/templates/example_hello_world/main.js

**Comment by mnmkng** [comment]
Oh, the template. TBH I don't like the `apify-core` example. It uses no features of the SDK and makes it look like you need to make HTTP requests and include `cheerio` separately.

**Comment by jancurn** [comment]
Well, any suggestions welcome, just create a PR
