### ISSUE TITLE
apify-cli push command console logs actor templates

### ISSUE THREAD

**Issue by nguyeda1** [apify/actor-templates#91]
Using `apify push` in CLI, logs the actor templates (see image). [Reported in slack](https://apifier.slack.com/archives/C0L33UM7Z/p1651234256412829).

I think [this line](https://github.com/apify/actor-templates/blob/c885fb37f347691bcf8eeddb8606a684bd21e02a/src/index.js#L32) might be the cause. In `apify-cli` repo it is called via `const { templates } = await actorTemplates.fetchManifest();`: [see here](https://github.com/apify/apify-cli/blob/6fb4ad12fa13594a65bf849e8ae82dae1f3f35e7/src/commands/push.js#L45)

<img width="1165" alt="Screen Shot 2022-04-29 at 14 10 25" src="https://user-images.githubusercontent.com/39300846/166205643-0958950f-1d2c-43d0-9923-04ea5746c864.png">

**Comment by mnmkng** [comment]
Fixed in https://github.com/apify/actor-templates/commit/4dabae8cf07d156799f070975d075d6abe0ff982

**Comment by mnmkng** [comment]
Fixed in https://github.com/apify/apify-cli/releases/tag/v0.7.4
