### ISSUE TITLE
Apify eslint configuration is not in the crawlee templates

### ISSUE THREAD

**Issue by petrpatek** [apify/actor-templates#94]
Historically the templates came with the development environment ready. I am not sure if the Apify eslint config is something we want all of the crawlee users to use, but it was excellent for Apify internal projects.

**Comment by B4nan** [comment]
Just an omission, no issue with using the apify configs, we do use them for tsconfig anyway (and moreover those are crawlee + actor sdk templates, ready for apify platform).

**Comment by B4nan** [comment]
Closing as we will be removing the crawlee templates from here. All the other templates are updated and use v3 already, we will move them to ESM and use the new features like router during next week.
